# Generated by Django 2.2.24 on 2021-09-30 18:58

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_prbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='assignment',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, help_text='Assignment from parameters (strings) to values (any JSON-compatible value)'),
        ),
    ]
