name: django-prbac test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        django-version: [ "3.2.*", "4.2.*" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip install django==${{ matrix.django-version }}
          pip install -e .
          pip install coverage coveralls
      - name: run tests
        run: |
          coverage run --source='django_prbac' `which django-admin.py` test django_prbac --settings django_prbac.mock_settings --traceback
      - name: report coverage stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage report 
          coveralls --service=github
